on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run build
      run: yarn build
    - name: INPUT
      run: |
        echo "Config:"
        cat config.yaml
        echo "========================"
        echo "Test:"
        cat test.yaml
    - name: OUTPUT
      run: node dist/yaml-sorter.js test.yaml
