on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run build
      run: yarn build
    - name: Print files
      run: cat test.yaml
    - name: Run test
      run: node dist/app.js
